source ~/.config/zsh/zim.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/path.zsh
source ~/.config/zsh/thefuck.zsh
source ~/.config/zsh/fzf.zsh
# source ~/fzf-tab-completion/zsh/fzf-zsh-completion.sh
# source ~/.config/zsh/completion.zsh


# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
