alias ls='ls --color'
alias cdiff='colordiff'
alias ra='ranger'
alias vim='nvim'
alias l='ls -al'
alias sudo='sudo -E'
alias s='neofetch'
alias t='tmux'
alias pip='pip3'
alias lg="lazygit"
alias cl='clear'
alias ipy="ipython"
